### ISSUE TITLE
Notification pop up

### ISSUE THREAD

**Issue by nadieenespecial** [rust-lang/rust-enhanced#356]
### Sublime Text Version
Build 3176

### Rust Enhanced Version
v2.18.0

### Operating system
Ubuntu 18.04.1 LTS

### Expected behavior
Easy to see. 
Is there any way to see it clearly regardless of the color scheme?

### Actual behavior
![screenshot from 2018-11-21 17-32-18](https://user-images.githubusercontent.com/43034851/48867250-558cff00-edb4-11e8-9816-0f1bf825c7d1.png)
![screenshot from 2018-11-21 17-42-14](https://user-images.githubusercontent.com/43034851/48867410-d2b87400-edb4-11e8-90b0-04ffbe5a4d7c.png)
![screenshot from 2018-11-21 17-43-53](https://user-images.githubusercontent.com/43034851/48867480-0a272080-edb5-11e8-828c-237cb1683897.png)

### Steps to reproduce
```
use std::io;

fn main() {
    println!("Adivina el número");
    println!("Ingrese un número");
    let mut respuesta = String::new();
    io::stdin().read_line(&mut respuesta);
    	// .expect("Error al leer la línea");
    println!("Adivinaste: {}", respuesta);
}
```

**Comment by ehuss** [comment]
I think this is a bug in the Seti_UX color scheme.  It overrides the phantom CSS like this:
```xml
<key>phantomCss</key>
<string><![CDATA[ html {position: relative; padding: 10px;} ]]></string>
```
which forces sublime to use the default CSS colors for phantoms.  The same problem occurs with inline errors for the built-in build system:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/43198/48871556-16ea4b00-ed9a-11e8-9aa4-b124a7d11b19.png">

There are a few options:
- Fix the Seti_UX color scheme.
    - One option is to add `background-color: var(--background);` to the `phantomCss` in the `.tmTheme` file.
- Set the `rust_syntax_*_color` settings in the Rust Enhanced settings to a darker color so that it is visible on a white background (unfortunately there are no options to change the background).
- Set `"rust_message_theme": "solid"` in the Rust Enhanced settings which sets a (hard-coded) background color.

**Comment by nadieenespecial** [comment]
>     * Set `"rust_message_theme": "solid"` in the Rust Enhanced settings which sets a (hard-coded) background color.
Thank you I used that.

![screenshot from 2018-11-26 04-53-24](https://user-images.githubusercontent.com/43034851/49000081-42bd5600-f137-11e8-9dc5-b613e9ac17cf.png)

**Comment by ehuss** [comment]
I'm going to close this for now, as it is a bug in a third-party color scheme.
