### ISSUE TITLE
Remove `print!` snippet

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust-enhanced#375]
Could the `print!` snippet be removed? Removing features sounds strange, but hear me out: 

I use `println` a lot for debugging (yes, I know `dbg!`, but `println` is often still necessary). To quickly write such a statement, I usually press `"pri" + <tab>`. However, this often leads to the `print!` snippet being used. However, I usually don't notice this right away, compile my application, run it only to find that my debugging output is not human readable, fix this mistake and compile again. Sounds like a simple problem, and maybe I'm indeed just too stupid, but you can't imagine how often this happened to me in the past months. I already tried to change my muscle memory to `"pril" + <tab>` but this didn't work well so far. It's so annoying :smile: 

Also note that `print!` is used substantially (!) less often than `println!`. I don't think a snippet is necessary for such a rare statement. 

---

#### Rust Enhanced Version
2.19

**Comment by ehuss** [comment]
I'm on the fence on this, but I agree sometimes it gets in the way.  You can train Sublime which completion it will default to. It picks the last one used for the characters typed so far. So you can do `p` then select `println`, then `pr`, select `println`, then `pri`, select `println`, etc.  so that it always defaults to println. However, that's not a great experience, and there's no way (I know of) to set priorities for snippets.  Thus I have opened #382 to remove them, I'll leave it open for a bit in case someone wants to comment on it.
