### ISSUE TITLE
Show inferred types of variables/expressions?

### ISSUE THREAD

**Issue by mcclure** [rust-lang/rust-enhanced#453]
### Sublime Text Version
Sublime Text 3.2.2 (Build 3211)

### Rust Enhanced Version
v2.23.0

### Operating system
MacOS 10.13.6 17G14033

### So uh
My favorite thing about the TypeScript sublime plugin, and the Merlin plugin for Objective Caml, is being able to cursor over a variable name and see its type. For an example of why this is useful, there is a line in the Rust program I am editing right now:

`let unwrapped = CString::new(name).unwrap();`

What is "unwrapped"? What does "unwrap" return? I don't know; I am new to Rust. I could dig into the docs and look up "CString", whatever package that's from, but in those other plugins for languages with inferred types it just asks the compiler to tell me what that variable's type is and that can speed up documentation dives considerably, especially for complex expressions. My "expected behavior" is there should be a feature for either putting the mouse or the text cursor over "unwrapped", and it would just tell me that variable's type.

If you already have a feature for this, it should be listed under "Features" in your documentation, because it isn't currently.

**Comment by urschrei** [comment]
AFAIK you need something like LSP for this. I use the sublime-lsp package and rust-analyzer as the actual language server. The former has a documented, pre-filled config for the latter, which has a pre-compiled macOS binary.

**Comment by mcclure** [comment]
Thanks. Do I install rust-analyzer via cargo or via something like homebrew?

**Comment by urschrei** [comment]
It's not available via cargo yet; the easiest thing to do is download the latest stable version (they cut a new release weekly):

1. Download the binary from https://github.com/rust-analyzer/rust-analyzer/releases, drop it in `$HOME/.cargo/bin` (there should be other binaries in there), and `chmod +x`. Depending on your security settings, you may have to open it once by right-clicking the binary and selecting `Open` in order to see and dismiss the codesigning dialog, at which point a new shell window should open, displaying `[snip]rust-analyzer ; exit;`. You can close this window

2.  Edit your sublime-lsp package settings (it appears as `LSP` in the list) to activate rust-analyzer by adding the following entry to the `clients` dict (in the right-hand pane):

```python
    "rust-analyzer":
    {
        "command":
        [
            "rust-analyzer"
        ],
        "enabled": true,
        "languageId": "rust",
        "scopes":
        [
            "source.rust"
        ],
        "syntaxes":
        [
            "Packages/Rust/Rust.sublime-syntax",
            "Packages/Rust Enhanced/RustEnhanced.sublime-syntax",
        ],
    }
```

3. Open a Rust project in Sublime, and open a source file. You _may_ have to enable sublime-lsp manually using the command palette (the command's called `LSP: Enable Language Server Globally).

4. Save, which should trigger rust-analyzer. If it's working, you'll see `rust-analyzer` in the status bar, and cargo check messages as the project dependencies build. If nothing happens when you save, try running the  `LSP: Restart Servers` command

5. Once rust-analyzer finishes running, you should see various annotations inline, as well as errors and warnings in a dedicated popup (this is all configurable via the sublime-lsp prefs)

6. If nothing's happening, have a look at Sublime's debug output (ctrl + `), which should show you a hopefully informative error.

**Comment by ehuss** [comment]
I'm going to close, as mentioned above using [rust-analyzer](https://rust-analyzer.github.io/) with the [LSP extension](https://lsp.sublimetext.io/) is the recommended way to go about getting enhanced information.
